/*
 * This source file was generated by the Gradle 'init' task
 */
package classex;

public class App {
    private static int sumOf(int n){
        int sum = 0;
        for (int i = 0; i< n; i++) {
            if (i % 5 == 0 || i % 7 == 0) {
                sum += 1;
            }
        }
        return sum;
    }
}
